export const Content = {
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  SET_HOLIDAYS_BELARUS: 'SET_HOLIDAYS_BELARUS',
  UPDATE_SELECTED_EVENTS: 'UPDATE_SELECTED_EVENTS',
  REMOVE_EVENT: 'REMOVE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
};
export const Parametr = {
  CHANGE_ACTIVE_MODAL: 'CHANGE_ACTIVE_MODAL',
  CHANGE_VIEW_FORMAT: 'CHANGE_VIEW_FORMAT',
  CHANGE_SHOW_BLOCK: 'CHANGE_SHOW_BLOCK',
  CHANGE_DATE: 'CHANGE_DATE',
  CHANGE_SELECTED_HOLIDAY: 'CHANGE_SELECTED_HOLIDAY',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_DATE_ONCLICK: 'CHANGE_DATE_ONCLICK',
  CHANGE_ACTIVE_POPUP: 'CHANGE_ACTIVE_POPUP',
};
