export const Content = {
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  ADD_EVENT: 'ADD_EVENT',
  SET_HOLIDAYS_BELARUS: 'SET_HOLIDAYS_BELARUS',
};
export const Parametr = {
  CHANGE_ACTIVE_MODAL: 'CHANGE_ACTIVE_MODAL',
  CHANGE_VIEW_FORMAT: 'CHANGE_VIEW_FORMAT',
  CHANGE_SHOW_BLOCK: 'CHANGE_SHOW_BLOCK',
  CHANGE_DATE: 'CHANGE_DATE',
  CHANGE_SELECTED_HOLIDAY: 'CHANGE_SELECTED_HOLIDAY',
};
